[platformio]

[env]
custom_firmware_version = placeholder
custom_host_name = placeholder 
custom_header_name = placeholder

platform = espressif32
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = chain+
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17
	-I src/config
	-I src/devices
	-I src/lib
	-I src/lib/modules
	; -D BUILD_TIMESTAMP=$UNIX_TIME

build_src_flags =
    -D HOSTNAME=\"${this.custom_host_name}\"
    -D FIRMWARE_VERSION=\"${this.custom_firmware_version}\"
	-D PROJECT_HEADER=devices/${this.custom_header_name}.h

extra_scripts = 
	myscript.py
	; post:gzipper.py
	pre:jsonFileToString.py
	pre:rebuild_main.py
	
lib_deps = 
	littlemanbuilds/ESP32_MCPWM@^1.0.0
	esp32async/ESPAsyncWebServer @ ^3.7.8
	bblanchon/ArduinoJson@^7.4.2
	fastled/FastLED@^3.9.13
	khoih-prog/ESP32TimerInterrupt @ ^2.3.0
	adafruit/Adafruit ADS1X15 @ 2.6.2
	adafruit/Adafruit BusIO @ 1.17.4
	
# --- Hardware Templates (Abstract) ---
#------S3 Mini----------------
# https://www.espboards.dev/esp32/esp32-s3-super-mini/
[hardware_s3_mini]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM
; lib_ldf_mode = chain+
build_flags =
	 ${env.build_flags}
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1


#------------S3 Dev Kit----------------
[hardware_s3_16mb]

board = esp32-s3-devkitc-1
board_build.psram_type = qio
board_build.arduino.memory_type = qio_qspi ;qio_opi causes board to crash
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
; lib_ldf_mode = chain+
build_flags =
	 ${env.build_flags}
	-D ARDUINO_USB_MODE=1

[hardware_mks_tinybee]
board = esp32Dev
upload_speed = 500000 ;slow down for stability with this board
board_build.flash_mode = dio
build_flags =
	 ${env.build_flags}
	-O2
	-D CORE_DEBUG_LEVEL=3
board_build.partitions = default.csv