[platformio]
default_envs = demo

extra_configs =
	platformio_base.ini

#-------------------------Projects----------------------------------
[wrapper]
custom_firmware_version = v1.0.11

[env:demo]
extends = wrapper, hardware_s3_mini
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = demo #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = device_demo

[env:demo2]
extends = wrapper, hardware_s3_mini
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = demo2 #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = demo

[env:bidet]
extends = wrapper, hardware_s3_mini
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = bidet #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = ${this.custom_host_name}

[env:garage_control]
extends = wrapper, hardware_s3_mini
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = garageS3 #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = ${this.custom_host_name}

[env:gate]
extends = wrapper, hardware_s3_mini
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = gate2 #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = ${this.custom_host_name}

[env:pool]
extends = wrapper, hardware_mks_tinybee
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = pool #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = ${this.custom_host_name}

[env:poolTest]
extends = wrapper, hardware_mks_tinybee
#wifi hostname,id, and header file name for this project. !!Case sensitive
custom_host_name = pool2 #!! Only (A-Z), (0-9) and hyphens. No spaces, underscores or other special characters
custom_header_name = pool